# Generated by Django 4.2.20 on 2025-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="기업 이름")),
                ("url", models.URLField(verbose_name="웹사이트 URL")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="주소"),
                ),
            ],
        ),
    ]
