# Generated by Django 4.2.20 on 2025-03-13 04:49

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="full_text",
            field=models.TextField(blank=True, null=True, verbose_name="전체 텍스트"),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.URLField(
                validators=[myapp.models.validate_url_format],
                verbose_name="웹사이트 URL",
            ),
        ),
    ]
