# Generated by Django 4.2.20 on 2025-03-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_company_full_text_alter_company_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="url",
        ),
        migrations.AlterField(
            model_name="company",
            name="full_text",
            field=models.TextField(default="", verbose_name="전체 텍스트"),
            preserve_default=False,
        ),
    ]
